# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1475844094);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1475844214);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1476022334);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.formfill.enable", false);
user_pref("browser.formfill.saveHttpsForms", false);
user_pref("browser.tabs.autoHide", true);
user_pref("dom.disable_window_flip", false);
user_pref("dom.disable_window_open_feature.status", false);
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "%7B899DF1F8-2F43-4394-8315-37F6744E6319%7D:1.0.9.1,codebender%40codebender.cc:1.7.0.0");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{899DF1F8-2F43-4394-8315-37F6744E6319}\":{\"descriptor\":\"F:\\\\Logiciels\\\\Arduino_graphique\\\\Blockly-at-rduino_AIO\\\\K-Meleon\\\\browser\\\\extensions\\\\{899DF1F8-2F43-4394-8315-37F6744E6319}.xpi\",\"mtime\":1426181465185}}},{\"name\":\"app-profile\",\"addons\":{\"codebender@codebender.cc\":{\"descriptor\":\"F:\\\\Logiciels\\\\Arduino_graphique\\\\Blockly-at-rduino_AIO\\\\K-Meleon\\\\Profiles\\\\3w6jnn5k.default\\\\extensions\\\\codebender@codebender.cc\",\"mtime\":1476004924418,\"rdfTime\":1474499916357}}}]");
user_pref("extensions.lastAppVersion", "31.8.0esr");
user_pref("extensions.lastPlatformVersion", "31.8.0esr");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://list/extension");
user_pref("extensions.ui.locale.hidden", true);
user_pref("font.name.fantasy.x-western", "3ds");
user_pref("general.useragent.contentlocale", "");
user_pref("general.useragent.locale", "fr");
user_pref("gfx.direct3d.last_used_feature_level_idx", 0);
user_pref("idle.lastDailyNotification", 1475844184);
user_pref("kmeleon.MRU.URL0", "http://technologiescollege.github.io/Blockly-at-rduino/");
user_pref("kmeleon.MRU.maxURLs", 0);
user_pref("kmeleon.display.XPos", 131);
user_pref("kmeleon.display.YPos", 174);
user_pref("kmeleon.display.accelInMenus", false);
user_pref("kmeleon.display.height", 31);
user_pref("kmeleon.display.maximized", true);
user_pref("kmeleon.display.statusbar", true);
user_pref("kmeleon.display.title", "Blockly@rduino");
user_pref("kmeleon.display.width", 132);
user_pref("kmeleon.download.SaveUnkownContent", false);
user_pref("kmeleon.download.saveDir", "C:\\Users\\babas\\Desktop\\");
user_pref("kmeleon.download.saveUseTitle", false);
user_pref("kmeleon.favicons.show", false);
user_pref("kmeleon.general.opengroup", "ID_OPEN_LINK|ID_OPEN_LINK_IN_BACKGROUND");
user_pref("kmeleon.general.toolbars_locked", false);
user_pref("kmeleon.install_firefox_extension", true);
user_pref("kmeleon.notab", true);
user_pref("kmeleon.plugins.bmpmenu.load", false);
user_pref("kmeleon.plugins.bookmarks.chevron", false);
user_pref("kmeleon.plugins.bookmarks.load", false);
user_pref("kmeleon.plugins.bookmarks.toolbarEnabled", false);
user_pref("kmeleon.plugins.fullscreen.last", false);
user_pref("kmeleon.plugins.fullscreen.load", false);
user_pref("kmeleon.plugins.macros.accel.mouse.configs", "Firefox;SeaMonkey;Opera;");
user_pref("kmeleon.plugins.macros.encoding.cache.size", 5);
user_pref("kmeleon.plugins.macros.proxy0.http.proxy.pipelining", true);
user_pref("kmeleon.plugins.macros.proxy0.http.proxy.version", "1.1");
user_pref("kmeleon.plugins.macros.reload.interval", 120);
user_pref("kmeleon.plugins.macros.translate.menu.regions", "1111111");
user_pref("kmeleon.plugins.macros.translate.service.langpairs", "");
user_pref("kmeleon.plugins.macros.translate.service.name", "&Google Translate");
user_pref("kmeleon.plugins.macros.translate.service.regions", "1111111");
user_pref("kmeleon.plugins.macros.translate.service.url.page", "http://translate.google.com/translate?u=<url>&hl=<to>&ie=UTF8&sl=<from>&tl=<to>");
user_pref("kmeleon.plugins.macros.translate.service.url.text", "http://translate.google.com/translate_t?langpair=<from>|<to>&text=<txt>");
user_pref("kmeleon.plugins.macros.translate.to", "en");
user_pref("kmeleon.plugins.macros.zoom", "text");
user_pref("kmeleon.plugins.privacy.clearCache", 1);
user_pref("kmeleon.plugins.privacy.clearCookies", 3);
user_pref("kmeleon.plugins.privacy.clearHistory", 3);
user_pref("kmeleon.plugins.privacy.clearMRU", 3);
user_pref("kmeleon.plugins.privacy.clearSignOn", 3);
user_pref("kmeleon.plugins.privacy.load", false);
user_pref("kmeleon.plugins.sessions.cleanShutdown", true);
user_pref("kmeleon.plugins.sessions.load", false);
user_pref("kmeleon.plugins.spellcheck.load", false);
user_pref("kmeleon.plugins.toolbars.load", false);
user_pref("kmeleon.plugins.update.lastcheck", 1475106992);
user_pref("kmeleon.plugins.update.load", false);
user_pref("kmeleon.prefs_inited", true);
user_pref("kmeleon.toolband.&Go Buttons.visibility", false);
user_pref("kmeleon.toolband.&Main Bar.visibility", false);
user_pref("kmeleon.toolband.&Privacy Bar.index", 13);
user_pref("kmeleon.toolband.&Privacy Bar.visibility", false);
user_pref("kmeleon.toolband.Bookmarks.index", 10);
user_pref("kmeleon.toolband.Browser Con&figuration.visibility", false);
user_pref("kmeleon.toolband.Tab/&Window Buttons.index", 12);
user_pref("kmeleon.toolband.Tab/&Window Buttons.visibility", false);
user_pref("kmeleon.toolband.Tabs.index", 11);
user_pref("kmeleon.toolband.URL Bar.visibility", false);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.http.proxy.pipelining", true);
user_pref("network.proxy.type", 4);
user_pref("places.database.lastMaintenance", 1475361400);
user_pref("places.history.expiration.transient_current_max_pages", 92576);
user_pref("plugin.importedState", true);
user_pref("signon.expireMasterPassword", false);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1475361400);
user_pref("toolkit.telemetry.previousBuildID", "7501");
user_pref("xpinstall.whitelist.add", "");
